controller_manager:
  ros__parameters:
    update_rate: 500  # Hz

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    joint_trajectory_controller:
      type: joint_trajectory_controller/JointTrajectoryController

    forward_position_controller:
      type: forward_command_controller/ForwardCommandController
    
    gripper_controller:
      type: forward_command_controller/ForwardCommandController

joint_trajectory_controller:
  ros__parameters:
    joints:
      - panda_joint1
      - panda_joint2
      - panda_joint3
      - panda_joint4
      - panda_joint5
      - panda_joint6
      - panda_joint7
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity
    state_publish_rate: 200.0 # Defaults to 50
    action_monitor_rate: 20.0 # Defaults to 20

    allow_partial_joints_goal: false # Defaults to false

    gains:
      panda_joint1: { p: 0.6, d: 0.3, i: 0., i_clamp: 1., ff_velocity_scale: 1. }
      panda_joint2: { p: 0.5, d: 0.2, i: 0., i_clamp: 1., ff_velocity_scale: 1. }
      panda_joint3: { p: 0.5, d: 0.2, i: 0., i_clamp: 1., ff_velocity_scale: 1. }
      panda_joint4: { p: 0.5, d: 0.2, i: 0., i_clamp: 1., ff_velocity_scale: 1. }
      panda_joint5: { p: 0.2, d: 0.1, i: 0., i_clamp: 1., ff_velocity_scale: 1. }
      panda_joint6: { p: 0.1, d: 0.05, i: 0., i_clamp: 1., ff_velocity_scale: 1. }
      panda_joint7: { p: 0.05, d: 0.01, i: 0., i_clamp: 1., ff_velocity_scale: 1. }

forward_position_controller:
  ros__parameters:
    joints:
      - panda_joint1
      - panda_joint2
      - panda_joint3
      - panda_joint4
      - panda_joint5
      - panda_joint6
      - panda_joint7
    interface_name: velocity

gripper_controller:
  ros__parameters:
    joints:
      - panda_finger_joint1
      - panda_finger_joint2
    interface_name: velocity
