my_simple_controllers:
  joints: {
    type: string_array,
    default_value: [],
    description: "Names of joints used by the controller",
    read_only: true,
    validation: {
      unique<>: null,
    }
  }
  state_interfaces: {
    type: string_array,
    default_value: [],
    description: "Names of state interfaces to claim",
    read_only: true,
    validation: {
      unique<>: null,
    }
  }
  state_publish_rate: {
    type: double,
    default_value: 100.0,
    description: "Frequency to publish state messages",
    read_only: true,
    validation: {
      gt_eq: [1.0]
    }
  }
